### ISSUE TITLE
Image too small

### ISSUE THREAD

**Issue by nitin-ppnp** [MakieOrg/MakieDraw.jl#4]
I want to annotate an image with 2D keypoints. Inspired by the example in the readme, I am using the following script 

## Script
```
using MakieDraw
using GLMakie
using GeometryBasics
using FileIO

img = load("/home/nitin/Downloads/IMG_20230302_104301389.jpg");
figure, axis = image(rot180(img),axis = (aspect = DataAspect(),))


categories = Observable(Int[])
point_canvas = GeometryCanvas{Point}(; 
  figure=figure, axis=axis, properties=(; categories), mouse_property=:categories,
  scatter_kw=(; color=categories, colorrange=(0, 2), colormap=:spring)
)
categories[]

point_canvas.active[] = true

layers = Dict(
    :point=>point_canvas.active,
)

MakieDraw.CanvasSelect(figure, axis; layers)
```

## Output
![image](https://github.com/MakieOrg/MakieDraw.jl/assets/18428565/a00c6637-b839-4a36-9c2b-4e149afe4dbd)

**Comment by rafaqz** [comment]
Yeah, I need to work out how to do this generically so it always works.

For now, create the canvas first and instead use `image!` to plot onto `canvas.axis`.

@SimonDanisch @jkrumbiegel this is the   control widget placement problem I was talking about.

We realy want the main axis filling most of the avalable space, with both the canvas dropdown and feature data input boxes knowing they should go together at the top, bottom or side in a control panel.

**Comment by nitin-ppnp** [comment]
I am trying this now. Looks fine, but the aspect ratio is incorrect.

## Script
```
using MakieDraw
using GLMakie
using GeometryBasics
using FileIO

figure = Figure()
axis = Axis(figure[1:10, 1:10], aspect = DataAspect())

img = load("/home/nitin/Downloads/IMG_20230302_104301389.jpg");
image!(rot180(img))


categories = Observable(Int[])
point_canvas = GeometryCanvas{Point}(; 
  figure=figure, axis=axis, properties=(; categories), mouse_property=:categories,
  scatter_kw=(; color=categories, colorrange=(0, 2), colormap=:spring)
)
categories[]

point_canvas.active[] = true

layers = Dict(
    :point=>point_canvas.active,
)

MakieDraw.CanvasSelect(figure, axis; layers)
```

## Output
![image](https://github.com/MakieOrg/MakieDraw.jl/assets/18428565/06456726-79a8-4807-b091-67d61462af00)

**Comment by rafaqz** [comment]
Aspect ratio is up to you to set, like any other Makie axis ;)

**Comment by jkrumbiegel** [comment]
What does GeometryCanvas and CamvasSelect do in terms of creating objects / modifying the layout? I'm wondering why it became so tiny in the upper example.

**Comment by rafaqz** [comment]
`GeometryCanvas` by default adds an axis and if you have a FeatureCollection with fields you want to edit it adds text boxes for them in a `GridLayout` row.

CanvasSelect just adds a dropdown.

Users could place all of these manually, its just a bit fiddly to do every time.

**Comment by jkrumbiegel** [comment]
Ah ok I see, well the top `Textbox` has `tellwidth = true` set, so the `Axis` above which has no predefined size adjusts down to its width. Because of the constrained aspect, it becomes tiny. For the control section, you'd usually want to define `tellwidth = false` on the containing GridLayout if it's placed above/below or `tellheight = false` if it's placed to the left/right.

**Comment by rafaqz** [comment]
Ahhh right I knew I was doing somethong fundamentally wrong somewhere 😅

See how far I get just fixing that

**Comment by jkrumbiegel** [comment]
something like 

```julia
Axis(f[1, 1])
controlgrid = GridLayout(f[1, 2], tellheight = false)
Button(controlgrid[1, 1], ...)
# etc
```

if you then want it somewhere else you do

```julia
f[2, 1] = controlgrid
trim!(f.layout)
controlgrid.tellheight = true
controlgrid.tellwidth = false
```

**Comment by nitin-ppnp** [comment]
> Aspect ratio is up to you to set, like any other Makie axis ;)

@rafaqz Sorry, but I am still not able to get intended output. I am getting the correct aspect ratio before using the `GeometryCanvas`. Here is the script and the output. The full script, as shown previously, mess up the aspect ratio.

## Script
```
using MakieDraw
using GLMakie
using GeometryBasics
using FileIO

figure = Figure()
axis = Axis(figure[1:10, 1:10], aspect = DataAspect())

img = load("/home/nitin/Downloads/IMG_20230302_104301389.jpg");
image!(rot180(img))
```
## Output
![image](https://github.com/MakieOrg/MakieDraw.jl/assets/18428565/049da675-a0f2-4030-aa28-609b1cdac33d)

I have also tried setting up the aspect ratio explicitly, but the same thing happened. I get the same aspect ratio as I set, before using the `GeometryCanvas`. The `GeometryCanvas` resets it to the same as we see in the previously shown example.

**Comment by rafaqz** [comment]
But you can set it on the `canvas.axis` *after* you have done everything else?

(I will try to fix, bit this is not my highest priority package right now so may be a while, wirking with the canvas.axis is your best chance in short term)

**Comment by nitin-ppnp** [comment]
Thanks! Setting it up afterward is working fine.
