### ISSUE TITLE
Documentation is not deployed

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/MakieDraw.jl#9]
Clicking on the links in the README leads to a 404.  We should fix that..

**Comment by felixcremer** [comment]
This is due to the wrong repo in this line of docs/make.jl
  repo="github.com/rafaqz/MakieDraw.jl"

This should be MakieOrg instead of rafaqz

**Comment by rafaqz** [comment]
Thanks I pushed a fix

**Comment by asinghvi17** [comment]
Is gh-pages set up?  I'm still getting a 404....

**Comment by rafaqz** [comment]
Yeah its still not deploying

**Comment by rafaqz** [comment]
Your caching may need a few more tweaks
https://github.com/MakieOrg/MakieDraw.jl/actions/runs/8767325108/job/24060438443#step:13:14

**Comment by asinghvi17** [comment]
Opened a PR for the caching.
Still no dice on the docs though...

**Comment by rafaqz** [comment]
The docs build now, but they're still not showing... and turns out I can't actually get to the setting page? 

I think someone needs to make me the owner of this package or an admin or something.

**Comment by asinghvi17** [comment]
@SimonDanisch would probably have to - this admin thing is a pain for most organizations I guess :D

**Comment by rafaqz** [comment]
@SimonDanisch bump on this, can I get admin rights here? I also want to set the "About" message...

**Comment by rafaqz** [comment]
Working now
